name: 'Tencent Accelerate COS Action(unofficial)'
description: 'GitHub Action for Tencent COS Command (coscmd) 全球加速域名专用，支持差异同步，适合静态网站'
author: 'Harris <i@xuegaogg.com>'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  args:
    description: 'COSCMD args, detail: https://cloud.tencent.com/document/product/436/10976'
    required: true
  secret_id:
    description: 'Tencent cloud SecretId, from: https://console.cloud.tencent.com/cam/capi'
    required: true
  secret_key:
    description: 'Tencent cloud SecretKey, from: https://console.cloud.tencent.com/cam/capi'
    required: true
  bucket:
    description: 'COS bucket name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
